name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tag-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get Latest Tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Create New Tag
        id: create_tag
        run: |
          version=$(echo ${{ steps.get_tag.outputs.latest_tag }} | awk -F. '{print $1"."$2"."$3 + 1}')
          git tag $version
          echo "new_tag=$version" >> $GITHUB_OUTPUT

      - name: Push Tag to Repository
        run: git push origin ${{ steps.create_tag.outputs.new_tag }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set version
        run: |
          echo "REACT_APP_VERSION=$(echo ${{ steps.create_tag.outputs.new_tag }})" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build
  
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: tag-build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
